name: Bug Report
description: Fehler melden
labels: [bug]
body:
  - type: textarea
    id: summary
    attributes:
      label: Beschreibung
      description: Was ist passiert?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Reproduktionsschritte
      description: Wie kann man den Fehler nachstellen?
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Erwartetes Verhalten
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Umgebung
      description: Browser, Gerät, Branch, Commit
