name: Feature Request
description: Neue Funktion vorschlagen
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: Welches Problem soll gelöst werden?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Vorschlag
      description: Was soll implementiert werden?
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Akzeptanzkriterien
      placeholder: |
        - [ ] ...
        - [ ] ...
